"""initial schema 9 tables

Revision ID: d90094c083ad
Revises: 
Create Date: 2026-10-08 14:31:30.580854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90094c083ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metric',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.Column('atm_iv', sa.Float(), nullable=False),
    sa.Column('iv_pct_40', sa.Float(), nullable=True),
    sa.Column('iv_pct_120', sa.Float(), nullable=True),
    sa.Column('curve_model', sa.String(length=16), nullable=True),
    sa.Column('curve_r2', sa.Float(), nullable=True),
    sa.Column('skew_25d', sa.Float(), nullable=True),
    sa.Column('term_slope', sa.Float(), nullable=True),
    sa.Column('vrp', sa.Float(), nullable=True),
    sa.Column('momentum_20d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('pipeline_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rows_fetched', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('open_px', sa.Float(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('close_px', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_reconcile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('per_contract_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('sample_n', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('by_regime_json', sa.JSON(), nullable=True),
    sa.Column('warn', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('engine', sa.String(length=16), nullable=False),
    sa.Column('signal', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_date'), 'signal', ['date'], unique=False)
    op.create_table('advice_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('verdict_json', sa.JSON(), nullable=True),
    sa.Column('card_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advice_card_signal_id'), 'advice_card', ['signal_id'], unique=False)
    op.create_table('execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_px', sa.Float(), nullable=True),
    sa.Column('slippage_bp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_log_signal_id'), 'execution_log', ['signal_id'], unique=False)
    op.create_table('position_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('mv', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('vega', sa.Float(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('iv', sa.Float(), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'position_id', name='uq_snap_date_pos')
    )
    op.create_index(op.f('ix_position_snapshot_date'), 'position_snapshot', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_snapshot_date'), table_name='position_snapshot')
    op.drop_table('position_snapshot')
    op.drop_index(op.f('ix_execution_log_signal_id'), table_name='execution_log')
    op.drop_table('execution_log')
    op.drop_index(op.f('ix_advice_card_signal_id'), table_name='advice_card')
    op.drop_table('advice_card')
    op.drop_index(op.f('ix_signal_date'), table_name='signal')
    op.drop_table('signal')
    op.drop_table('review_log')
    op.drop_table('position_reconcile')
    op.drop_table('position')
    op.drop_table('pipeline_run')
    op.drop_table('daily_metric')
    # ### end Alembic commands ###
